import type { Metadata } from "next";
import { Geist, Geist_Mono, Urbanist } from "next/font/google";
import "./globals.css";
import Header from "./component/Header";

const urbanist = Urbanist({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Sasu lloyd",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-screen">
      <body className={urbanist.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
